# Minimalist Visitor Map Configuration
# Simple, privacy-friendly visitor distribution display

# Visitor Map Settings
visitor_map:
  enabled: true                    # Enable/disable the visitor map
  layout: "bottom-page"           # Fixed at bottom of page (not floating)
  center_region: "china"          # Map centered on China
  show_on_mobile: true            # Show on mobile devices
  track_region_only: true         # Only track region/continent, not exact location
  max_regions_stored: 20          # Maximum number of region visits to store
  demo_mode: false               # Enable demo mode for testing
  
  # Styling options (simplified)
  style:
    max_width: "800px"            # Maximum width of map container
    height: "200px"               # Map height (desktop)
    mobile_height: "150px"        # Map height (mobile)
    background: "#f8f9fa"         # Light background
    border_radius: "8px"          # Subtle rounded corners
    
  # Color scheme (minimalist)
  colors:
    background: "#f8f9fa"         # Widget background
    continent: "#90caf9"          # Continent color
    china_highlight: "#4fc3f7"    # China highlighted in different color
    visitor_dot: "#ff5722"        # Visitor dot color (subtle red)
    text: "#495057"               # Text color
    
  # Map settings (simplified)
  map:
    show_only_regions: true       # Show regions, not countries
    animate_new_visitors: true    # Subtle pulse animation for new visitors
    china_centered: true          # Map projection centered on China
    
  # Privacy settings (enhanced)
  privacy:
    no_ip_storage: true           # Never store IP addresses
    store_ip_addresses: false     # Don't store actual IP addresses
    region_level_only: true       # Only track continent/region level
    no_city_data: true            # Don't show or store city information
    anonymize_location: false     # Show exact city or anonymize to country level
    no_timestamps_display: false # Don't display visit times
    respect_do_not_track: true    # Respect browser's do-not-track setting
